### ISSUE TITLE
[FEAT] Handle Tink Transaction Product

### ISSUE THREAD

**Issue by ccoeurderoy** [algoan/nestjs-tink-connector#20]
## Description

Tink has evolved its aggregation product into two separate products: [Account Check](https://docs.tink.com/resources/account-check) and [Transactions](https://docs.tink.com/resources/transactions).

Today, the Tink connector only supports the Account Aggregation product which Tink has deprecated. This issue lists changes that need to be applied.

⚠️ **We won't add the Account Check product for now because it requires an extra implementation in order to bundle both products**

### Aggregator Link Required

The Tink Link iframe URL is not precisely the same as the Account Aggregation product. So it needs to be updated. Refer to the [Tink documentation](https://docs.tink.com/resources/transactions/connect-to-a-bank-account).

### Bank details required

To fetch accounts and transactions, two new APIs have to be called:

- `GET https://api.tink.com/data/v2/accounts`
- `GET https://api.tink.com/data/v2/transactions?accountIdn=...`

Call then the `PATCH .../analyses/:analysisId` with the `TINK_V2` format.

⚠️**We need to keep the v1 API calls for Tink in order to handle both products. We should create a new config to redirect properly existing service accounts to the v2**

**Comment by LeKer29** [comment]
It seems coherent with my investigations. I did not know there was an impact on the iframe part, good to know.

**Comment by LeKer29** [comment]
`⚠️We need to keep the v1 API calls for Tink in order to handle both products.` => in which case(s) we need to call v1 API ?

`We should create a new config to redirect properly existing service accounts to the v2` => what do you mean by new config ?

**Comment by ccoeurderoy** [comment]
> in which case(s) we need to call v1 API ?

Some clients still might use the Account Aggregation product which is based on the v1. To avoid handling two instances of the Tink Connector, we could handle it easily with a configuration attached to the Service Account to inform the connector that the corresponding SA is based on Transactions Product or not.

**Comment by ccoeurderoy** [comment]
@LeKer29 I've got some news about the Continuous access: with the v2, it is not pricing dependent. So if the Service Account is set to the v2 of Tink, we should only consider the "Continuous access". Why? Because if we want to enable easily the multi-bank connection mode, it is easier to handle this with the Continuous Access mode. From Tink Support:

> Hmm so if you want to connect several banks from the same user I think it makes more sense to go for Continuous Access. This way you’d be able to create and manage users and to see a coherent connection of a user to all their bank accounts. 
It is also possible with one-time access; when an end user authenticates two times towards two different banks, it will normally result in two Tink Users being created on your end. You can then of course collate the data you receive from these two Tink Users into a single user of your app. 

What do you think about that?
